#!/bin/bash

set -eu

filesystem=$1
fw_env_source="$LAYER_DIR/../../u-boot/fw_env.config"
ab_tool_source="$LAYER_DIR/../../u-boot/masjidpi-ab"
confirm_service_source="$LAYER_DIR/../../u-boot/masjidpi-ab-confirm.service"

test -f "$fw_env_source"
test -x "$ab_tool_source"
test -f "$confirm_service_source"

install -d -o root -g root -m 0700 \
    "$filesystem/persistent/iwd" \
    "$filesystem/var/lib/iwd"

if [[ -n "${IGconf_iwd_profile:-}" ]]; then
    test -f "$IGconf_iwd_profile"

    install -o root -g root -m 0600 \
        "$IGconf_iwd_profile" \
        "$filesystem/persistent/iwd/$(basename "$IGconf_iwd_profile")"
fi

install -d -m 0755 \
    "$filesystem/etc" \
    "$filesystem/usr/local/sbin" \
    "$filesystem/usr/lib/systemd/system" \
    "$filesystem/etc/systemd/system/multi-user.target.wants"

install -m 0644 \
    "$fw_env_source" \
    "$filesystem/etc/fw_env.config"

install -m 0755 \
    "$ab_tool_source" \
    "$filesystem/usr/local/sbin/masjidpi-ab"

install -m 0644 \
    "$confirm_service_source" \
    "$filesystem/usr/lib/systemd/system/masjidpi-ab-confirm.service"

ln -sfn \
    /usr/lib/systemd/system/masjidpi-ab-confirm.service \
    "$filesystem/etc/systemd/system/multi-user.target.wants/masjidpi-ab-confirm.service"
