"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const startup = fs.readFileSync(path.join(root, "frontend/masjidboard-startup.html"), "utf8");
const html = fs.readFileSync(path.join(root, "frontend/setup.html"), "utf8");
const css = fs.readFileSync(path.join(root, "frontend/setup.css"), "utf8");
const js = fs.readFileSync(path.join(root, "frontend/setup.js"), "utf8");

assert.match(startup, /http:\/\/127\.0\.0\.1:8080\/appliance/);
assert.match(html, /Set up MasjidFrame/);
assert.match(html, /Choose your 2\.4 GHz Wi-Fi network/);
assert.match(html, /id="wifiPassword"[^>]*readonly/);
assert.match(html, /id="keyboard"[^>]*aria-label="On-screen keyboard"/);
assert.match(html, /id="addHiddenNetwork"[^>]*>Add hidden network</);
assert.match(html, /id="wifiSSID"[^>]*readonly/);
assert.match(html, /id="hiddenSecurity"/);
assert.match(html, /id="returnToBoard"[^>]*href="\/masjidboard\.html\?profile=appliance"[^>]*hidden/);
assert.match(html, /id="locationStep"/);
assert.match(html, /id="countryButton"[^>]*class="picker-button"/);
assert.match(html, /id="regionButton"[^>]*class="picker-button"/);
assert.match(html, /id="cityButton"[^>]*class="picker-button"/);
assert.match(html, /id="pickerSheet"[^>]*aria-modal="true"/);
assert.match(html, /id="masjidStep"/);
assert.match(html, /More setup options/);
assert.match(html, /configure Listen, audio, additional masjids, and display preferences/);
assert.match(html, /id="fqdnURL"/);
assert.match(html, /id="ipURL"/);
assert.match(css, /@media \(orientation: landscape\)/);
assert.match(css, /\.key\s*\{[^}]*height: 54px/s);
assert.match(css, /\.masjid-option\s*\{[^}]*margin: 0/s);
assert.match(css, /body\.masjid-step-open #masjidStep\s*\{[^}]*display: flex;[^}]*min-height: 0;[^}]*flex: 1 1 auto/s);
assert.match(css, /body\.masjid-step-open #finishSetupButton\s*\{[^}]*flex: 0 0 auto/s);
assert.match(js, /\/api\/setup\/wifi\/networks/);
assert.match(js, /\/api\/setup\/wifi\/connect/);
assert.match(js, /hidden: currentNetwork\.hidden/);
assert.match(js, /function addHiddenNetwork/);
assert.match(js, /activeKeyboardInput/);
assert.match(js, /setupParams\.get\("return"\) === "board"/);
assert.match(js, /\/api\/setup\/device-access/);
assert.match(js, /`http:\/\/\$\{access\.fqdn\}:\$\{port\}`/);
assert.match(js, /`http:\/\/\$\{access\.ip_address\}:\$\{port\}`/);
assert.match(js, /\/api\/masjidboard\/hierarchy\/refresh/);
assert.match(js, /\/api\/masjidboard\/scope/);
assert.match(js, /\/api\/masjidboard\/catalogue\/refresh/);
assert.match(js, /\/api\/masjidboard\/selection/);
assert.match(js, /selection\?\.configured === true/);
assert.match(js, /requestedStep === "location"/);
assert.match(js, /function openPicker/);
assert.match(js, /classList\.add\("masjid-step-open"\)/);
assert.match(js, /className = "picker-option"/);
assert.doesNotMatch(html, /<select/);
assert.match(js, /const symbolRows/);
assert.match(js, /const letterRows = \[\s*\["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"\]/s);
assert.match(js, /symbols: "#\+="/);
assert.match(js, /activeKeyboardInput\.value = Array\.from\(activeKeyboardInput\.value\)\.slice\(0, -1\)/);
assert.doesNotMatch(js, /innerHTML\s*=.*network\.ssid/);

console.log("MasjidFrame first-run setup UI tests passed");
