"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "frontend/masjidboard.html"), "utf8");
const css = fs.readFileSync(path.join(root, "frontend/masjidboard-appliance.css"), "utf8");
const themes = fs.readFileSync(path.join(root, "frontend/masjidboard-themes.css"), "utf8");
const themeController = fs.readFileSync(path.join(root, "frontend/masjidboard-theme.js"), "utf8");
const config = fs.readFileSync(path.join(root, "frontend/masjidboard-config.html"), "utf8");
const layoutController = fs.readFileSync(path.join(root, "frontend/masjidboard-layout-config.js"), "utf8");
const controller = fs.readFileSync(path.join(root, "frontend/masjidboard-touch-controls.js"), "utf8");
const appliance = fs.readFileSync(path.join(root, "frontend/masjidboard-appliance.js"), "utf8");

assert.match(html, /id="applianceListenPanel"/);
assert.match(html, /class="appliance-listen-close"[^>]*aria-label="Close Listen controls"><\/button>/);
assert.match(html, /masjidboard-appliance\.css\?v=20260906-light-themes/);
assert.match(html, /↑ Swipe up for controls/);
assert.doesNotMatch(html, /id="applianceOpenListenPanel"/);
assert.match(html, /data-touch-tab="masjid"/);
assert.match(html, /data-touch-tab="radio"/);
assert.match(html, /data-touch-tab="theme"/);
assert.match(html, /data-touch-tab="network"/);
assert.match(html, /data-touch-panel="network"/);
assert.match(html, /id="applianceChangeWiFi"[^>]*href="\/setup\.html\?return=board"/);
assert.match(html, /id="applianceNetworkFQDN"/);
assert.match(html, /id="applianceNetworkIP"/);
assert.match(html, /On another device connected to this network/);
assert.match(html, /Change Wi-Fi network/);
assert.match(html, /Scheduled Play/);
assert.match(html, /Play Now/);
assert.match(html, /Stop Radio/);
assert.match(html, /Master Volume/);
assert.match(html, /Masjid Volume/);
assert.match(html, /Radio Volume/);
assert.match(controller, /params\.get\("profile"\) !== "appliance"/);
assert.match(controller, /dy < -70/);
assert.doesNotMatch(controller, /portrait/);
assert.match(controller, /dy > 45/);
assert.match(controller, /target\.setPointerCapture\?\.\(event\.pointerId\)/);
assert.match(controller, /event\.target\.closest\("button,a,input"\)/);
assert.match(controller, /panel\.addEventListener\("pointermove"/);
assert.match(controller, /panel\.addEventListener\("pointercancel"/);
assert.match(controller, /event\.preventDefault\(\)/);
assert.doesNotMatch(controller, /appliance-listen-close"\)\?\.focus\(\)/);
assert.match(controller, /\/api\/favourites/);
assert.match(controller, /\/api\/listen\/radio-mode/);
assert.match(controller, /\/api\/masjidboard\/layout/);
assert.match(controller, /\/api\/setup\/device-access/);
assert.match(controller, /`http:\/\/\$\{fqdn\}:\$\{port\}`/);
assert.match(controller, /`http:\/\/\$\{ipAddress\}:\$\{port\}`/);
assert.match(controller, /button\.dataset\.sourceId = item\.id/);
assert.match(controller, /selectSource\("masjid", button\.dataset\.sourceId\)/);
assert.match(controller, /selectSource\("radio", button\.dataset\.sourceId\)/);
assert.doesNotMatch(controller, /dataset\.sourceID/);
assert.match(controller, /control\.addEventListener\("input", \(\) => scheduleVolumeSave\(name\)\)/);
assert.match(controller, /window\.setTimeout\(\(\) => saveVolume\(name, value\), 120\)/);
assert.match(controller, /const inactivityTimeout = 60000/);
assert.match(controller, /inactivityTimer = window\.setTimeout\(\(\) => setOpen\(false\), inactivityTimeout\)/);
assert.match(controller, /\["pointerdown", "keydown", "input", "change"\]/);
assert.match(controller, /addEventListener\("scroll", resetInactivityTimer, true\)/);
assert.match(controller, /pendingVolumes\[name\] \?\? values\[name\]/);
assert.match(controller, /\{volume:value, persist:true\}/);
assert.match(controller, /volumeOutputs\.master\.textContent = status\.master_volume_supported \? `\$\{masterVolume\.value\}%` : "Unavailable"/);
assert.match(controller, /playMasjid\.textContent = selectedMasjidPlaying \? "Masjid Playing" : "▶ Play Masjid"/);
assert.match(controller, /\["black-white", "Black & White"/);
assert.match(controller, /\["light", "Light Gold"/);
assert.match(controller, /\["ivory", "Ivory"/);
assert.match(controller, /\["sage", "Sage"/);
assert.match(controller, /\["sky", "Sky"/);
assert.match(controller, /\["rose", "Rose"/);
assert.match(appliance, /masjidpi:appliance-listen-panel/);
assert.doesNotMatch(appliance, /portrait/);
assert.match(css, /var\(--appliance-panel\)/);
assert.match(css, /\.appliance-listen-sheet\s*\{[^}]*height:724px/s);
assert.match(css, /\.appliance-listen-content\s*\{[^}]*flex:1 1 auto;[^}]*min-height:0/s);
assert.match(css, /\.appliance-listen-status\s*\{[^}]*height:76px;[^}]*flex:0 0 76px/s);
assert.match(css, /\.appliance-listen-close::before,\.appliance-listen-close::after\s*\{[^}]*top:50%;[^}]*left:50%;[^}]*transform:translate\(-50%,-50%\) rotate\(45deg\)/s);
assert.match(css, /\.appliance-listen-close::after\s*\{[^}]*rotate\(-45deg\)/s);
assert.match(css, /\.appliance-listen-heading\s*\{[^}]*touch-action:none/s);
assert.match(css, /\.appliance-theme-option\s*\{[^}]*height:62px/s);
assert.match(css, /\.appliance-theme-grid\s*\{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/s);
assert.match(css, /\.appliance-network-settings a\s*\{[^}]*min-height:52px/s);
assert.match(css, /\.appliance-network-address b\s*\{[^}]*overflow-wrap/);
assert.match(css, /\.appliance-listen-tabs\s*\{[^}]*grid-template-columns:repeat\(4,1fr\)/s);
assert.match(css, /\.appliance-listen-tabs button\.active\s*\{[^}]*color:var\(--appliance-highlight-text\)/s);
assert.doesNotMatch(css, /portrait/);
assert.match(themes, /--appliance-danger:var\(--danger\)/);
assert.match(themes, /body\.appliance-layout\[data-board-theme="light"\]\s*\{\s*--appliance-highlight-text:#fff;/);
for (const theme of ["ivory", "sage", "sky", "rose"]) {
    assert.match(themeController, new RegExp(`"${theme}"`));
    assert.match(layoutController, new RegExp(`"${theme}"`));
    assert.match(config, new RegExp(`name="boardTheme" value="${theme}"`));
    assert.match(themes, new RegExp(`body\\[data-board-theme="${theme}"\\]`));
}
assert.match(config, /value="light"[^>]*>[\s\S]*?<strong>Light Gold<\/strong>/);

console.log("MasjidBoard appliance touch-control tests passed");
