"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "frontend/masjidboard.html"), "utf8");
const css = fs.readFileSync(path.join(root, "frontend/masjidboard-appliance.css"), "utf8");
const themes = fs.readFileSync(path.join(root, "frontend/masjidboard-themes.css"), "utf8");
const controller = fs.readFileSync(path.join(root, "frontend/masjidboard-touch-controls.js"), "utf8");
const appliance = fs.readFileSync(path.join(root, "frontend/masjidboard-appliance.js"), "utf8");

assert.match(html, /id="applianceListenPanel"/);
assert.match(html, /class="appliance-listen-close"[^>]*aria-label="Close Listen controls"><\/button>/);
assert.match(html, /masjidboard-appliance\.css\?v=20260831-centred-close-control/);
assert.match(html, /↑ Swipe up for controls/);
assert.doesNotMatch(html, /id="applianceOpenListenPanel"/);
assert.match(html, /data-touch-tab="masjid"/);
assert.match(html, /data-touch-tab="radio"/);
assert.match(html, /data-touch-tab="theme"/);
assert.match(html, /Scheduled Play/);
assert.match(html, /Play Now/);
assert.match(html, /Stop Radio/);
assert.match(html, /Master Volume/);
assert.match(html, /Masjid Volume/);
assert.match(html, /Radio Volume/);
assert.match(controller, /params\.get\("profile"\) !== "appliance"/);
assert.match(controller, /dy < -70/);
assert.doesNotMatch(controller, /portrait/);
assert.match(controller, /dy > 70/);
assert.match(controller, /\/api\/favourites/);
assert.match(controller, /\/api\/listen\/radio-mode/);
assert.match(controller, /\/api\/masjidboard\/layout/);
assert.match(controller, /button\.dataset\.sourceId = item\.id/);
assert.match(controller, /selectSource\("masjid", button\.dataset\.sourceId\)/);
assert.match(controller, /selectSource\("radio", button\.dataset\.sourceId\)/);
assert.doesNotMatch(controller, /dataset\.sourceID/);
assert.match(controller, /control\.addEventListener\("input", \(\) => scheduleVolumeSave\(name\)\)/);
assert.match(controller, /window\.setTimeout\(\(\) => saveVolume\(name, value\), 120\)/);
assert.match(controller, /const inactivityTimeout = 60000/);
assert.match(controller, /inactivityTimer = window\.setTimeout\(\(\) => setOpen\(false\), inactivityTimeout\)/);
assert.match(controller, /\["pointerdown", "keydown", "input", "change"\]/);
assert.match(controller, /addEventListener\("scroll", resetInactivityTimer, true\)/);
assert.match(controller, /pendingVolumes\[name\] \?\? values\[name\]/);
assert.match(controller, /\{volume:value, persist:true\}/);
assert.match(controller, /volumeOutputs\.master\.textContent = status\.master_volume_supported \? `\$\{masterVolume\.value\}%` : "Unavailable"/);
assert.match(controller, /playMasjid\.textContent = selectedMasjidPlaying \? "Masjid Playing" : "▶ Play Masjid"/);
assert.match(controller, /\["black-white", "Black & White"/);
assert.match(appliance, /masjidpi:appliance-listen-panel/);
assert.doesNotMatch(appliance, /portrait/);
assert.match(css, /var\(--appliance-panel\)/);
assert.match(css, /\.appliance-listen-sheet\s*\{[^}]*height:724px/s);
assert.match(css, /\.appliance-listen-content\s*\{[^}]*flex:1 1 auto;[^}]*min-height:0/s);
assert.match(css, /\.appliance-listen-status\s*\{[^}]*height:76px;[^}]*flex:0 0 76px/s);
assert.match(css, /\.appliance-listen-close::before,\.appliance-listen-close::after\s*\{[^}]*top:50%;[^}]*left:50%;[^}]*transform:translate\(-50%,-50%\) rotate\(45deg\)/s);
assert.match(css, /\.appliance-listen-close::after\s*\{[^}]*rotate\(-45deg\)/s);
assert.match(css, /\.appliance-theme-option\s*\{[^}]*height:84px/s);
assert.doesNotMatch(css, /portrait/);
assert.match(themes, /--appliance-danger:var\(--danger\)/);

console.log("MasjidBoard appliance touch-control tests passed");
