device:
  layer: rpi3
  hostname: masjidframe
  user1: masjidframe
  user1pass: "MasjidFrame786!"
#device:
#  layer: rpi3
#  hostname: masjidframe

image:
  layer: masjidframe-pi3-ab-prototype
  boot_part_size: 256M
  system_part_size: 4G
  data_part_size: 5G
  name: masjidframe-pi3-ab-prototype

layer:
  base: masjidframe-trixie-minbase
